/**
 * @Copyright:   SuperAwesome Trading Limited 2017
 * @Author:      Gabriel Coman (gabriel.coman@superawesome.tv)
 */

#import <UIKit/UIKit.h>
#import "FlashRuntimeExtensions2.h"

/**
 * C method that sends a call back to the AIR SDK with data suitable for CPI.
 *
 * @param context       current FREContext object
 * @param name          AIR ad name to send the callback to. This should be
 *                      unique and generated by the SDK
 * @param success       whether the CPI callback was a success
 * @param callack       callback method name
 */
void sendCPICallback (FREContext context, NSString *name, BOOL success, NSString *callack);
